# Generated by Django 2.2 on 2019-04-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=120)),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
    ]
