# Generated by Django 2.2 on 2019-04-22 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlist',
            name='url',
        ),
        migrations.AddField(
            model_name='uploadlist',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
